# Generated by Django 4.2.2 on 2023-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=1000)),
                ('img', models.ImageField(blank=True, upload_to='projects')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
