# Generated by Django 4.2.7 on 2023-11-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='extracurricular',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
